version: '3.4'

services:
  ordiniservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionString=server=sqlOrdiniService.data;Database=OrderDB;User Id=SA;Password=yourStrong(!)Password@word;Encrypt=True;TrustServerCertificate=True;
      - RabbitMQHostname=rabbitmq
      - RabbitMQPort=5672
      - RabbitMQUsername=user
      - RabbitMQPassword=password
      - RabbitMQQueueName=OrdiniService_Queue
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  prodottiservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8082
      - ASPNETCORE_HTTPS_PORTS=8083
      - ConnectionString=server=sqlProdottiService.data;Database=ProductDB;User Id=SA;Password=yourStrong(!)Password@word;Encrypt=True;TrustServerCertificate=True;
      - RabbitMQHostname=rabbitmq
      - RabbitMQPort=5672
      - RabbitMQUsername=user
      - RabbitMQPassword=password
      - RabbitMQQueueName=ProdottiService_Queue
    ports:
      - "8082"
      - "8083"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8084
      - ASPNETCORE_HTTPS_PORTS=8085
      - RabbitMQHostname=rabbitmq
      - RabbitMQPort=5672
      - RabbitMQUsername=user
      - RabbitMQPassword=password
      - RabbitMQQueueName=ApiGateway_Queue
      - RabbitMQQueueNameOrders=OrdiniService_Queue
      - RabbitMQQueueNameProducts=ProdottiService_Queue
    ports:
      - "8084"
      - "8085"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
